apiVersion: apps/v1
kind: Deployment
metadeta:
  name: devops-app-deployment
spec:
  replica: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
  spec:
    containers:
    - name: devops-app-container
      image: priyankasivakumar98/k8s
      ports:
      - containerPort: 9000

